import os
import json
import glob
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# ─────────────────────────────────────────
OUTPUT_DIR      = r"E:\shorts_pipeline\output"
CLIENT_SECRETS  = r"E:\shorts_pipeline\client_secrets.json"
TOKEN_FILE      = r"E:\shorts_pipeline\token.json"
SCOPES          = ["https://www.googleapis.com/auth/youtube.upload"]
# ─────────────────────────────────────────


def get_authenticated_service():
    creds = None

    if os.path.exists(TOKEN_FILE):
        creds = Credentials.from_authorized_user_file(TOKEN_FILE, SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(CLIENT_SECRETS, SCOPES)
            creds = flow.run_local_server(port=0)

        with open(TOKEN_FILE, "w") as f:
            f.write(creds.to_json())

    return build("youtube", "v3", credentials=creds)


def get_latest_video():
    runs = sorted(glob.glob(os.path.join(OUTPUT_DIR, "*")), reverse=True)
    for run in runs:
        manifest_path = os.path.join(run, "manifest.json")
        video_path    = os.path.join(run, "final_short.mp4")
        if os.path.exists(manifest_path) and os.path.exists(video_path):
            with open(manifest_path, "r", encoding="utf-8") as f:
                manifest = json.load(f)
            if manifest["status"].get("phase5_upload"):
                continue  # already uploaded
            return run, manifest, video_path
    raise ValueError("Koi nai video nahi mili upload ke liye.")


def upload_video(youtube, video_path, title, description):
    print(f"\n  Uploading: {video_path}")
    print(f"  Title: {title}")

    body = {
        "snippet": {
            "title":       title[:100],
            "description": description,
            "tags":        ["shorts", "ai", "news", "automation"],
            "categoryId":  "25",  # News & Politics
        },
        "status": {
            "privacyStatus": "private",  # pehle private — check karo phir public karo
        }
    }

    media = MediaFileUpload(
        video_path,
        mimetype="video/mp4",
        resumable=True,
        chunksize=1024*1024
    )

    request  = youtube.videos().insert(part="snippet,status", body=body, media_body=media)
    response = None

    print("  Uploading", end="", flush=True)
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f".", end="", flush=True)

    print(f"\n  ✓ Uploaded! Video ID: {response['id']}")
    print(f"  URL: https://youtube.com/watch?v={response['id']}")
    return response["id"]


def run_upload():
    print("\n=== Phase 5: YouTube Upload ===\n")

    run_dir, manifest, video_path = get_latest_video()
    print(f"  Run folder: {run_dir}")

    title       = manifest["script"].get("title", "AI News Short")
    source_title = manifest["source"].get("title", "")
    description = f"{source_title}\n\nGenerated by AI automation pipeline.\n\n#Shorts #AI #News"

    youtube  = get_authenticated_service()
    video_id = upload_video(youtube, video_path, title, description)

    # manifest update karo
    manifest["status"]["phase5_upload"] = True
    manifest["youtube_video_id"]        = video_id
    manifest["youtube_url"]             = f"https://youtube.com/watch?v={video_id}"

    with open(os.path.join(run_dir, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    print(f"\n✓ Phase 5 complete!")
    print(f"  YouTube URL: https://youtube.com/watch?v={video_id}")
    return video_id


if __name__ == "__main__":
    run_upload()
